services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  web:
    build: .
    command: ./url-shortner
    ports:
      - "8080:8080"