services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mydb", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ./url-shortner
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000